### ISSUE TITLE
Speakers with UTF-8 characters (äöü) are not parsed correctly

### ISSUE THREAD

**Issue by JohannesRabauer** [xdev-software/sessionize-java-client#74] opened 2024-02-29 10:13 UTC

**Comment by AB-xdev** [comment] 2024-02-29 10:23
The problem is that the JVM is using not UTF8 as default encoding.

However ``ApiClient#deserialize`` should also not use scanner and better use ``EntityUtils#toString`` instead as this method correctly derives the charset from the encountered response.

**Comment by AB-xdev** [comment] 2024-02-29 10:27
Problem is located inside OpenAPI generator:
https://github.com/OpenAPITools/openapi-generator/blob/d4e10508cdc7ff50a1addad2ebffd56ebc1f2556/modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache#L854-L867

**Comment by AB-xdev** [comment] 2024-02-29 10:29
Same problem is described here: https://github.com/OpenAPITools/openapi-generator/issues/16818

**Comment by AB-xdev** [comment] 2024-02-29 11:01
Create upstream PR: https://github.com/OpenAPITools/openapi-generator/pull/17998

If we don't get a fix in the next days we will patch this manually.

**Comment by AB-xdev** [comment] 2024-03-26 12:26
Fixed by OpenAPIGenerator 7.4+ in https://github.com/xdev-software/sessionize-java-client/commit/f5fcaacdc1ca3cc9612403a92b9accffd4596ac7#diff-26ec5e493924f1952b7725db35d35c8e5173efac2525b3620dbe03be7a1c9b11

**Closed by AB-xdev** 2024-03-26 12:26 UTC
Labels: bug
